# Default values for DTO
# This is a YAML-formatted file.

# Global settings
global:
  imageRegistry: ""
  imagePullSecrets: []

# API Backend configuration
api:
  image:
    repository: dto/api
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  
  replicaCount: 2
  
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: dto-api.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: dto-api-tls
        hosts:
          - dto-api.example.com
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  
  # Security policies (secure defaults from BRD)
  policies:
    externalAiEnabled: false
    sqlPreviewEnabled: false
    adminPowerMode: false
    piiRedactionEnabled: true
    staticSecretsForbidden: true
    networkIsolation: true
    runRetentionDays: 90
    artifactRetentionDays: 30
  
  # Database configuration
  database:
    type: postgresql
    host: dto-postgresql
    port: 5432
    name: dto
    existingSecret: dto-db-secret
    existingSecretPasswordKey: password
  
  # Artifact storage configuration
  artifactStorage:
    type: s3
    bucket: dto-artifacts
    region: us-east-1
    existingSecret: dto-storage-secret
  
  # Environment variables
  env:
    LOG_LEVEL: INFO
    CORS_ORIGINS: "https://dto.example.com"
  
  # Health checks
  livenessProbe:
    httpGet:
      path: /api/v1/healthz
      port: 8000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  readinessProbe:
    httpGet:
      path: /api/v1/readyz
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Frontend configuration
frontend:
  image:
    repository: dto/frontend
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  
  replicaCount: 2
  
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: dto.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: dto-frontend-tls
        hosts:
          - dto.example.com
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
  
  env:
    NEXT_PUBLIC_API_URL: "https://dto-api.example.com/api/v1"

# PostgreSQL database (using Bitnami chart)
postgresql:
  enabled: true
  auth:
    postgresPassword: "changeme"
    username: "dto"
    password: "changeme"
    database: "dto"
  primary:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: ""
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
  metrics:
    enabled: true

# Redis for caching (optional)
redis:
  enabled: false
  auth:
    enabled: true
    password: "changeme"
  master:
    persistence:
      enabled: true
      size: 8Gi

# Monitoring
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      app: dto
  
  grafana:
    enabled: true
    dashboards:
      enabled: true

# Security
security:
  podSecurityPolicy:
    enabled: true
  
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
    egress:
      enabled: true
  
  rbac:
    create: true
  
  serviceAccount:
    create: true
    annotations: {}
    name: ""

# Node selector and tolerations
nodeSelector: {}
tolerations: []
affinity: {}

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1
